/**
 * StagCopyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.MiscController;
const SelfActivateDepretiatedRequest = testerlib.SelfActivateDepretiatedRequest;
const Body = testerlib.Body;
const CreateEventRequest = testerlib.CreateEventRequest;
const Paginated = testerlib.Paginated;
const CreateOneWithPassword = testerlib.CreateOneWithPassword;
const Header = testerlib.Header;
const EditAnEventRequest = testerlib.EditAnEventRequest;
const Scope = testerlib.Scope;
const FailureException = testerlib.FailureException;
const Verification = testerlib.Verification;
const LogInAuthoriseRequest = testerlib.LogInAuthoriseRequest;
const FailureOnNotActivatedUserException = testerlib.FailureOnNotActivatedUserException;
const Success = testerlib.Success;


describe("MiscController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Get Admin Token for tests

### Return
```JSON
{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdGFnLmxvY2FsIiwic3ViIjoiNWNjZGFhMzI4YjYyZDU1MzIwM2Y5Y2MwIiwic2NvcGUiOlsicmVndWxhciJdLCJqdGkiOiI4MDU3MTY4Zi1mNWQxLTRjYTItODY1MS01ZmQ5YzNjMmUxODkiLCJpYXQiOjE1NTczMjQ5NzgsImV4cCI6MTU1NzMyODU3OH0.IBmfNqU_uLjl2rettx9InzLjuCkH1zDKp1JIH6TomVg"
}
```
     */
    it("should testLocalhost8000AuthTestToken response", function testLocalhost8000AuthTestTokenTest(done) {
        controller.getLocalhost8000AuthTestToken(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        }).catch(() => undefined);
    });
});
