/**
 * StagCopyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Body
 */
class Body extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.iss = this.constructor.getValue(obj.iss);
        this.sub = this.constructor.getValue(obj.sub);
        this.scope = this.constructor.getValue(obj.scope);
        this.jti = this.constructor.getValue(obj.jti);
        this.iat = this.constructor.getValue(obj.iat);
        this.exp = this.constructor.getValue(obj.exp);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'iss', realName: 'iss' },
            { name: 'sub', realName: 'sub' },
            { name: 'scope', realName: 'scope', array: true },
            { name: 'jti', realName: 'jti' },
            { name: 'iat', realName: 'iat' },
            { name: 'exp', realName: 'exp' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Body;
