/**
 * StagCopyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateEventRequest
 */
class CreateEventRequest extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.startsAt = this.constructor.getValue(obj.startsAt || obj.starts_at);
        this.endsAt = this.constructor.getValue(obj.endsAt || obj.ends_at);
        this.title = this.constructor.getValue(obj.title);
        this.creator = this.constructor.getValue(obj.creator);
        this.location = this.constructor.getValue(obj.location);
        this.description = this.constructor.getValue(obj.description);
        this.attendees = this.constructor.getValue(obj.attendees);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'startsAt', realName: 'starts_at' },
            { name: 'endsAt', realName: 'ends_at' },
            { name: 'title', realName: 'title' },
            { name: 'creator', realName: 'creator' },
            { name: 'location', realName: 'location' },
            { name: 'description', realName: 'description' },
            { name: 'attendees', realName: 'attendees', array: true },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateEventRequest;
