/**
 * StagCopyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SelfActivateDepretiatedRequest = require('../lib/Models/SelfActivateDepretiatedRequest');
const Body = require('../lib/Models/Body');
const CreateEventRequest = require('../lib/Models/CreateEventRequest');
const Paginated = require('../lib/Models/Paginated');
const CreateOneWithPassword = require('../lib/Models/CreateOneWithPassword');
const Header = require('../lib/Models/Header');
const EditAnEventRequest = require('../lib/Models/EditAnEventRequest');
const Scope = require('../lib/Models/Scope');
const Verification = require('../lib/Models/Verification');
const LogInAuthoriseRequest = require('../lib/Models/LogInAuthoriseRequest');
const Success = require('../lib/Models/Success');
const FailureException = require('../lib/Exceptions/FailureException');
const FailureOnNotActivatedUserException =
  require('../lib/Exceptions/FailureOnNotActivatedUserException');

const classMap = {
    SelfActivateDepretiatedRequest,
    Body,
    CreateEventRequest,
    Paginated,
    CreateOneWithPassword,
    Header,
    EditAnEventRequest,
    Scope,
    Verification,
    LogInAuthoriseRequest,
    Success,
    FailureException,
    FailureOnNotActivatedUserException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
