/**
 * StagCopyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const _request = require('../Http/Client/RequestClient');
const _configuration = require('../configuration');
const _servers = require('../Servers');
const _apiHelper = require('../APIHelper');
const _baseController = require('./BaseController');

class MiscController {
    /**
     * Get Admin Token for tests
     * ### Return
     * ```JSON
     * {
     * "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.
     * eyJpc3MiOiJzdGFnLmxvY2FsIiwic3ViIjoiNWNjZGFhMzI4YjYyZDU1MzIwM2Y5Y2MwIiwic2NvcGUiOlsicmVndW
     * xhciJdLCJqdGkiOiI4MDU3MTY4Zi1mNWQxLTRjYTItODY1MS01ZmQ5YzNjMmUxODkiLCJpYXQiOjE1NTczMjQ5Nzgs
     * ImV4cCI6MTU1NzMyODU3OH0.IBmfNqU_uLjl2rettx9InzLjuCkH1zDKp1JIH6TomVg"
     * }
     * ```
     *
     * @callback    The callback function that returns response from the API call
     *
     * @returns {Promise}
     */
    static getLocalhost8000AuthTestToken(callback) {
        // create empty callback if absent
        const _callback = typeof callback === 'function' ? callback : () => undefined;

        // prepare query string for API call
        const _baseUri = _configuration.getBaseUri(_servers.SERVER_2);

        const _pathUrl = '/auth/test_token';
        const _queryBuilder = `${_baseUri}${_pathUrl}`;

        // validate and preprocess url
        const _queryUrl = _apiHelper.cleanUrl(_queryBuilder);

        // prepare headers
        const _headers = {
            'user-agent': 'APIMATIC 2.0',
        };

        // construct the request
        const _options = {
            queryUrl: _queryUrl,
            method: 'GET',
            headers: _headers,
        };

        // build the response processing.
        return new Promise((_fulfill, _reject) => {
            _request(_options, (_error, _response, _context) => {
                let errorResponse;
                if (_error) {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                } else if (_response.statusCode >= 200 && _response.statusCode <= 206) {
                    _callback(null, null, _context);
                    _fulfill();
                } else {
                    errorResponse = _baseController.validateResponse(_context);
                    _callback(errorResponse.error, errorResponse.response, errorResponse.context);
                    _reject(errorResponse.error);
                }
            });
        });
    }
}
module.exports = MiscController;
